version: "3"

services:
  lms:
    build:
        context: ./build
# Uncomment the following lines to install nightly.
#        args:
#            LMS_VERSION: 7.9.1
    image: beargarden/logitechmediaserver
    container_name: lms
    volumes:
      - ${AUDIO_DIR}:/music:ro
      - ${PLAYLIST_DIR}:/playlists:rw
      - ${CONFIG_DIR}:/config
    tmpfs: /tmp
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    restart: always
    environment:
      - NO_SLIMP3=false
      - NO_MYSQUEEZEBOX=false
      - NO_IMAGE=true
      - NO_VIDEO=true
      - NO_WEB=false
      - NO_ADMIN=false
      - SOX_OPTS=--buffer 20000 --temp /tmp
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
