version: "3"

services:
  lms:
    build:
        context: ./build
    image: beargarden/logitechmediaserver
    container_name: lms
    volumes:
      - ${AUDIO_DIR}:/music:ro
      - ${PLAYLIST_DIR}:/playlists:rw
      - ${CONFIG_DIR}:/config
    tmpfs: /tmp
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SOX_OPTS=${SOX_OPTS}
      - NO_SLIMP3=${NO_SLIMP3}
      - NO_MYSQUEEZEBOX=${NO_MYSQUEEZEBOX}
      - NO_IMAGE=${NO_IMAGE}
      - NO_VIDEO=${NO_VIDEO}
      - NO_WEB=${NO_WEB}
      - NO_ADMIN=${NO_ADMIN}
